export const TWEETS_ACT_ISLOADINGERROR = 'TWEETS_ACT_ISLOADINGERROR';
export const TWEETS_ACT_ISLOADING = 'TWEETS_ACT_ISLOADING';
export const TWEETS_ACT_LOADINGSUCCESS = 'TWEETS_ACT_LOADINGSUCCESS';
export const MENU_ACT_CHANGEACTIVEMANU = 'MENU_ACT_CHANGEACTIVEMANU';
