export const TWEETS_ACT_ISLOADINGERROR = 'TWEETS_ACT_ISLOADINGERROR';
export const TWEETS_ACT_ISLOADING = 'TWEETS_ACT_ISLOADING';
export const TWEETS_ACT_LOADINGSUCCESS = 'TWEETS_ACT_LOADINGSUCCESS';
export const MENU_ACT_CHANGEACTIVEMANU = 'MENU_ACT_CHANGEACTIVEMANU';
export const TWEETS_ACT_ADDTWEET = 'TWEETS_ACT_ADDTWEET';
export const TWEETS_ACT_FAVORITE = 'TWEETS_ACT_FAVORITE';
export const TWEETS_ACT_REPLY = 'TWEETS_ACT_REPLY';
export const SAVE_DRAFT = 'SAVE_DRAFT';

